spring:
  config:
    import: ["classpath:application-secret.yml"]
  security:
    paths:
      public: /auth/login, /auth/test, /auth/register
    jwt:
      ttl_minutes: 15

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_rest
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: db/migration/main-changelog.xml

  jpa:
    properties:
      hibernate:
        connection:
          isolation: READ_COMMITTED
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none

server:
  address:
    "127.0.0.1"
  port:
    "8080"

springdoc:
  packagesToScan: com.example.bankcards.controller
  enable-spring-security: true

