spring:
  config:
    import: ["classpath:application-secret.yml"]
  security:
    paths:
      public: /auth/login, /auth/test, /auth/register
    jwt:
      ttl_minutes: 15

  datasource:
    url: jdbc:postgresql://localhost:5432/bank_rest
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  address:
    "127.0.0.1"
  port:
    "8080"



